// Generated by fixie at 16-03-2024 14:29
package fixie

import java.lang.Math.*

private const val RAW_ONE = 100000

@JvmInline
value class FixDisplacement private constructor(val raw: Int) : Comparable<FixDisplacement> {

	override fun toString(): String {
		val intPart = raw / RAW_ONE
		var fractPart = (raw % RAW_ONE).toString().replace("-", "")
		while (fractPart.length < 5) fractPart = "0$fractPart"
		fractPart = ".$fractPart"
		while (fractPart.endsWith('0')) fractPart = fractPart.substring(0 until fractPart.length - 1)
		if (fractPart == ".") fractPart = ""
		val minus = if (raw < 0 && intPart == 0) "-" else ""
		return "$minus$intPart$fractPart"
	}

	fun toInt() = raw / RAW_ONE

	fun toLong() = (raw / RAW_ONE).toLong()

	fun toFloat() = toDouble().toFloat()

	fun toDouble() = raw.toDouble() / RAW_ONE.toDouble()

	@Throws(FixedPointException::class)
	operator fun unaryMinus() = if (raw != Int.MIN_VALUE)
		FixDisplacement(-raw) else throw FixedPointException("Can't negate MIN_VALUE")

	@Throws(FixedPointException::class)
	operator fun plus(right: FixDisplacement): FixDisplacement {
		try {
			return FixDisplacement(addExact(this.raw, right.raw))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Tried to compute $this + $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun plus(right: Int) = this + from(right)

	@Throws(FixedPointException::class)
	operator fun plus(right: Long) = this + from(right)

	@Throws(FixedPointException::class)
	operator fun plus(right: Float) = this + from(right)

	@Throws(FixedPointException::class)
	operator fun plus(right: Double) = this + from(right)

	@Throws(FixedPointException::class)
	operator fun minus(right: FixDisplacement): FixDisplacement {
		try {
			return FixDisplacement(subtractExact(this.raw, right.raw))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Tried to compute $this - $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun minus(right: Int) = this - from(right)

	@Throws(FixedPointException::class)
	operator fun minus(right: Long) = this - from(right)

	@Throws(FixedPointException::class)
	operator fun minus(right: Float) = this - from(right)

	@Throws(FixedPointException::class)
	operator fun minus(right: Double) = this - from(right)

	@Throws(FixedPointException::class)
	operator fun times(right: FixDisplacement): FixDisplacement {
		val largeValue = this.raw.toLong() * right.raw.toLong()
		try {
			return FixDisplacement(toIntExact(largeValue / RAW_ONE))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Can't represent $this * $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun times(right: Int): FixDisplacement {
		try {
			return FixDisplacement(multiplyExact(raw, right))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Can't represent $this * $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun times(right: Long): FixDisplacement {
		try {
			return FixDisplacement(toIntExact(multiplyExact(raw.toLong(), right)))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Can't represent $this * $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun times(right: Float) = this * from(right)

	@Throws(FixedPointException::class)
	operator fun times(right: Double) = this * from(right)

	@Throws(FixedPointException::class)
	operator fun div(right: FixDisplacement): FixDisplacement {
		val largeValue = this.raw.toLong() * RAW_ONE.toLong()
		try {
			return FixDisplacement(toIntExact(largeValue / right.raw))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Can't represent $this / $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun div(right: Int): FixDisplacement {
		if (right == 0 || (raw == Int.MIN_VALUE && right == -1)) {
			throw FixedPointException("Can't represent $this / $right")
		}
		return FixDisplacement(raw / right)
	}

	@Throws(FixedPointException::class)
	operator fun div(right: Long): FixDisplacement {
		if (right == 0L || (raw == Int.MIN_VALUE && right == -1L)) {
			throw FixedPointException("Can't represent $this / $right")
		}
		return FixDisplacement(toIntExact(raw.toLong() / right))
	}

	@Throws(FixedPointException::class)
	operator fun div(right: Float) = this / from(right)

	@Throws(FixedPointException::class)
	operator fun div(right: Double) = this / from(right)

	override operator fun compareTo(other: FixDisplacement) = this.raw.compareTo(other.raw)

	operator fun compareTo(other: Int) = if (other < -21474) 1 else if (other > 21474) -1 else this.compareTo(from(other))

	operator fun compareTo(other: Long) = if (other < -21474) 1 else if (other > 21474) -1 else this.compareTo(from(other))
	operator fun compareTo(other: Float) = if (other < -21474.836f) 1 else if (other > 21474.836f) -1 else this.compareTo(from(other))
	operator fun compareTo(other: Double) = if (other < -21474.83648) 1 else if (other > 21474.83647) -1 else this.compareTo(from(other))

	companion object {

		val ZERO = from(0)
		val ONE = from(1)

		fun raw(rawValue: Int) = FixDisplacement(rawValue)

		@Throws(FixedPointException::class)
		fun from(value: Int): FixDisplacement {
			try {
				return FixDisplacement(multiplyExact(value, RAW_ONE))
			} catch (overflow: ArithmeticException) {
				throw FixedPointException("Can't represent $value")
			}
		}

		@Throws(FixedPointException::class)
		fun from(value: Long): FixDisplacement {
			try {
				return from(toIntExact(value))
			} catch (overflow: ArithmeticException) {
				throw FixedPointException("Can't represent $value")
			}
		}

		fun from(value: Float) = from(value.toDouble())

		@Throws(FixedPointException::class)
		fun from(value: Double): FixDisplacement {
			val doubleValue = RAW_ONE.toDouble() * value
			if (doubleValue > Int.MAX_VALUE.toDouble() || doubleValue < Int.MIN_VALUE.toDouble()) {
				throw FixedPointException("Can't represent $value")
			}
			return FixDisplacement(round(doubleValue).toInt())
		}
	}

	@JvmInline
	value class Array private constructor(val raw: IntArray) {

		constructor(size: Int) : this(IntArray(size))

		constructor(size: Int, initializer: (Int) -> FixDisplacement) : this(IntArray(size) { index -> initializer(index).raw })

		val size: Int
			get() = raw.size

		operator fun get(index: Int) = FixDisplacement(raw[index])

		operator fun set(index: Int, value: FixDisplacement) {
			raw[index] = value.raw
		}

		fun fill(value: FixDisplacement) {
			raw.fill(value.raw)
		}
	}
}

@Throws(FixedPointException::class)
operator fun Int.plus(right: FixDisplacement) = FixDisplacement.from(this) + right

@Throws(FixedPointException::class)
operator fun Long.plus(right: FixDisplacement) = FixDisplacement.from(this) + right

@Throws(FixedPointException::class)
operator fun Float.plus(right: FixDisplacement) = FixDisplacement.from(this) + right

@Throws(FixedPointException::class)
operator fun Double.plus(right: FixDisplacement) = FixDisplacement.from(this) + right

@Throws(FixedPointException::class)
operator fun Int.minus(right: FixDisplacement) = FixDisplacement.from(this) - right

@Throws(FixedPointException::class)
operator fun Long.minus(right: FixDisplacement) = FixDisplacement.from(this) - right

@Throws(FixedPointException::class)
operator fun Float.minus(right: FixDisplacement) = FixDisplacement.from(this) - right

@Throws(FixedPointException::class)
operator fun Double.minus(right: FixDisplacement) = FixDisplacement.from(this) - right

@Throws(FixedPointException::class)
operator fun Int.times(right: FixDisplacement) = right * this

@Throws(FixedPointException::class)
operator fun Long.times(right: FixDisplacement) = right * this

@Throws(FixedPointException::class)
operator fun Float.times(right: FixDisplacement) = right * this

@Throws(FixedPointException::class)
operator fun Double.times(right: FixDisplacement) = right * this

@Throws(FixedPointException::class)
operator fun Int.div(right: FixDisplacement) = FixDisplacement.from(this) / right

@Throws(FixedPointException::class)
operator fun Long.div(right: FixDisplacement) = FixDisplacement.from(this) / right

@Throws(FixedPointException::class)
operator fun Float.div(right: FixDisplacement) = FixDisplacement.from(this) / right

@Throws(FixedPointException::class)
operator fun Double.div(right: FixDisplacement) = FixDisplacement.from(this) / right

operator fun Int.compareTo(right: FixDisplacement) = FixDisplacement.from(this).compareTo(right)

operator fun Long.compareTo(right: FixDisplacement) = FixDisplacement.from(this).compareTo(right)

operator fun Float.compareTo(right: FixDisplacement) = FixDisplacement.from(this).compareTo(right)

operator fun Double.compareTo(right: FixDisplacement) = FixDisplacement.from(this).compareTo(right)

@Throws(FixedPointException::class)
fun abs(value: FixDisplacement) = if (value.raw != Int.MIN_VALUE) FixDisplacement.raw(kotlin.math.abs(value.raw))
		else throw FixedPointException("Can't represent abs of min value")

fun min(a: FixDisplacement, b: FixDisplacement) = FixDisplacement.raw(kotlin.math.min(a.raw, b.raw))

fun max(a: FixDisplacement, b: FixDisplacement) = FixDisplacement.raw(kotlin.math.max(a.raw, b.raw))
