// Generated by fixie at 30-08-2024 09:38
package fixie.generator.floatvsfixed

@JvmInline
value class Displacement internal constructor(val value: FixedNumber) : Comparable<Displacement> {

	fun toDouble(unit: DistanceUnit) = when (unit) {
		DistanceUnit.PICOMETER -> value.toDouble() * 1.0E12
		DistanceUnit.NANOMETER -> value.toDouble() * 1.0E9
		DistanceUnit.MICROMETER -> value.toDouble() * 1000000.0
		DistanceUnit.MILLIMETER -> value.toDouble() * 1000.0
		DistanceUnit.INCH -> value.toDouble() * 39.37007874015748
		DistanceUnit.FOOT -> value.toDouble() * 3.280839895013123
		DistanceUnit.YARD -> value.toDouble() * 1.0936132983377076
		DistanceUnit.METER -> value.toDouble()
		DistanceUnit.KILOMETER -> value.toDouble() * 0.001
		DistanceUnit.MILE -> value.toDouble() * 6.213711922373339E-4
	}

	override fun toString() = toString(DistanceUnit.METER)

	fun toString(unit: DistanceUnit): String {
		val rawDouble = raw(1).toDouble(unit)
		var numDecimalDigits = 0
		var referenceValue = 0.88
		while (rawDouble < referenceValue) {
			referenceValue *= 0.1
			numDecimalDigits += 1
		}
		return String.format("%.${numDecimalDigits}f%s", toDouble(unit), unit.abbreviation)
	}

	override operator fun compareTo(other: Displacement) = this.value.compareTo(other.value)

	@Throws(FixedPointException::class)
	operator fun unaryMinus() = Displacement(-value)

	@Throws(FixedPointException::class)
	operator fun plus(right: Displacement) = Displacement(this.value + right.value)

	@Throws(FixedPointException::class)
	operator fun minus(right: Displacement) = Displacement(this.value - right.value)

	@Throws(FixedPointException::class)
	operator fun times(right: Int) = Displacement(this.value * right)

	@Throws(FixedPointException::class)
	operator fun div(right: Int) = Displacement(this.value / right)

	@Throws(FixedPointException::class)
	operator fun times(right: Long) = Displacement(this.value * right)

	@Throws(FixedPointException::class)
	operator fun div(right: Long) = Displacement(this.value / right)

	@Throws(FixedPointException::class)
	operator fun times(right: FixedNumber) = Displacement(this.value * right)

	@Throws(FixedPointException::class)
	operator fun div(right: FixedNumber) = Displacement(this.value / right)

	@Throws(FixedPointException::class)
	operator fun times(right: Float) = Displacement(FixedNumber.from(this.value.toDouble() * right))

	@Throws(FixedPointException::class)
	operator fun div(right: Float) = Displacement(FixedNumber.from(this.value.toDouble() / right))

	@Throws(FixedPointException::class)
	operator fun times(right: Double) = Displacement(FixedNumber.from(this.value.toDouble() * right))

	@Throws(FixedPointException::class)
	operator fun div(right: Double) = Displacement(FixedNumber.from(this.value.toDouble() / right))

	operator fun div(right: Displacement) = this.value.toDouble() / right.value.toDouble()

	companion object {

		fun raw(value: Int) = Displacement(FixedNumber.raw(value))

		val METER = raw(32768)

		val MILE = raw(52734984)

		val KILOMETER = raw(32768000)

		val YARD = raw(29963)

		val FOOT = raw(9988)

		val INCH = raw(832)

		val MILLIMETER = raw(33)
	}
}

@Throws(FixedPointException::class)
operator fun Int.times(right: Displacement) = right * this

@Throws(FixedPointException::class)
operator fun Long.times(right: Displacement) = right * this

@Throws(FixedPointException::class)
operator fun Float.times(right: Displacement) = right * this

@Throws(FixedPointException::class)
operator fun Double.times(right: Displacement) = right * this

@Throws(FixedPointException::class)
operator fun FixedNumber.times(right: Displacement) = right * this

@Throws(FixedPointException::class)
fun abs(x: Displacement) = Displacement(abs(x.value))

fun min(a: Displacement, b: Displacement) = Displacement(min(a.value, b.value))

fun max(a: Displacement, b: Displacement) = Displacement(max(a.value, b.value))
