// Generated by fixie at 30-08-2024 09:38
package fixie.generator.floatvsfixed

import java.math.BigInteger
import java.lang.Math.*

private const val RAW_ONE = 32768

@JvmInline
value class FixedNumber private constructor(val raw: Int) : Comparable<FixedNumber> {

	override fun toString(): String {
		val intPart = raw / RAW_ONE
		val bigFract = BigInteger.valueOf((raw % RAW_ONE).toLong()) * BigInteger.valueOf(100000)
		val fractNumber = bigFract / BigInteger.valueOf(RAW_ONE.toLong())
		var fractPart = fractNumber.toString().replace("-", "")
		while (fractPart.length < 5) fractPart = "0$fractPart"
		fractPart = ".$fractPart"
		while (fractPart.endsWith('0')) fractPart = fractPart.substring(0 until fractPart.length - 1)
		if (fractPart == ".") fractPart = ""
		val minus = if (raw < 0 && intPart == 0) "-" else ""
		return "$minus$intPart$fractPart"
	}

	fun toInt() = raw / RAW_ONE

	fun toLong() = (raw / RAW_ONE).toLong()

	fun toFloat() = toDouble().toFloat()

	fun toDouble() = raw.toDouble() / RAW_ONE.toDouble()

	@Throws(FixedPointException::class)
	operator fun unaryMinus() = if (raw != Int.MIN_VALUE)
		FixedNumber(-raw) else throw FixedPointException("Can't negate MIN_VALUE")

	@Throws(FixedPointException::class)
	operator fun plus(right: FixedNumber): FixedNumber {
		try {
			return FixedNumber(addExact(this.raw, right.raw))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Tried to compute $this + $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun plus(right: Int) = this + from(right)

	@Throws(FixedPointException::class)
	operator fun plus(right: Long) = this + from(right)

	@Throws(FixedPointException::class)
	operator fun plus(right: Float) = this + from(right)

	@Throws(FixedPointException::class)
	operator fun plus(right: Double) = this + from(right)

	@Throws(FixedPointException::class)
	operator fun minus(right: FixedNumber): FixedNumber {
		try {
			return FixedNumber(subtractExact(this.raw, right.raw))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Tried to compute $this - $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun minus(right: Int) = this - from(right)

	@Throws(FixedPointException::class)
	operator fun minus(right: Long) = this - from(right)

	@Throws(FixedPointException::class)
	operator fun minus(right: Float) = this - from(right)

	@Throws(FixedPointException::class)
	operator fun minus(right: Double) = this - from(right)

	@Throws(FixedPointException::class)
	operator fun times(right: FixedNumber): FixedNumber {
		val largeValue = this.raw.toLong() * right.raw.toLong()
		try {
			return FixedNumber(toIntExact(largeValue shr 15))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Can't represent $this * $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun times(right: Int): FixedNumber {
		try {
			return FixedNumber(multiplyExact(raw, right))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Can't represent $this * $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun times(right: Long): FixedNumber {
		try {
			return FixedNumber(toIntExact(multiplyExact(raw.toLong(), right)))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Can't represent $this * $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun times(right: Float) = this * from(right)

	@Throws(FixedPointException::class)
	operator fun times(right: Double) = this * from(right)

	@Throws(FixedPointException::class)
	operator fun div(right: FixedNumber): FixedNumber {
		val largeValue = this.raw.toLong() shl 15
		try {
			return FixedNumber(toIntExact(largeValue / right.raw))
		} catch (overflow: ArithmeticException) {
			throw FixedPointException("Can't represent $this / $right")
		}
	}

	@Throws(FixedPointException::class)
	operator fun div(right: Int): FixedNumber {
		if (right == 0 || (raw == Int.MIN_VALUE && right == -1)) {
			throw FixedPointException("Can't represent $this / $right")
		}
		return FixedNumber(raw / right)
	}

	@Throws(FixedPointException::class)
	operator fun div(right: Long): FixedNumber {
		if (right == 0L || (raw == Int.MIN_VALUE && right == -1L)) {
			throw FixedPointException("Can't represent $this / $right")
		}
		return FixedNumber(toIntExact(raw.toLong() / right))
	}

	@Throws(FixedPointException::class)
	operator fun div(right: Float) = this / from(right)

	@Throws(FixedPointException::class)
	operator fun div(right: Double) = this / from(right)

	override operator fun compareTo(other: FixedNumber) = this.raw.compareTo(other.raw)

	operator fun compareTo(other: Int) = if (other < -65536) 1 else if (other > 65535) -1 else this.compareTo(from(other))

	operator fun compareTo(other: Long) = if (other < -65536) 1 else if (other > 65535) -1 else this.compareTo(from(other))
	operator fun compareTo(other: Float) = if (other < -65536.0f) 1 else if (other > 65536.0f) -1 else this.compareTo(from(other))
	operator fun compareTo(other: Double) = if (other < -65536.0) 1 else if (other > 65535.99996948242) -1 else this.compareTo(from(other))

	companion object {

		val ZERO = from(0)
		val ONE = from(1)

		fun raw(rawValue: Int) = FixedNumber(rawValue)

		@Throws(FixedPointException::class)
		fun from(value: Int): FixedNumber {
			try {
				return FixedNumber(multiplyExact(value, RAW_ONE))
			} catch (overflow: ArithmeticException) {
				throw FixedPointException("Can't represent $value")
			}
		}

		@Throws(FixedPointException::class)
		fun from(value: Long): FixedNumber {
			try {
				return from(toIntExact(value))
			} catch (overflow: ArithmeticException) {
				throw FixedPointException("Can't represent $value")
			}
		}

		fun from(value: Float) = from(value.toDouble())

		@Throws(FixedPointException::class)
		fun from(value: Double): FixedNumber {
			val doubleValue = RAW_ONE.toDouble() * value
			if (doubleValue > Int.MAX_VALUE.toDouble() || doubleValue < Int.MIN_VALUE.toDouble()) {
				throw FixedPointException("Can't represent $value")
			}
			return FixedNumber(round(doubleValue).toInt())
		}
	}

	@JvmInline
	value class Array private constructor(val raw: IntArray) {

		constructor(size: Int) : this(IntArray(size))

		constructor(size: Int, initializer: (Int) -> FixedNumber) : this(IntArray(size) { index -> initializer(index).raw })

		val size: Int
			get() = raw.size

		operator fun get(index: Int) = FixedNumber(raw[index])

		operator fun set(index: Int, value: FixedNumber) {
			raw[index] = value.raw
		}

		fun fill(value: FixedNumber) {
			raw.fill(value.raw)
		}
	}
}

@Throws(FixedPointException::class)
operator fun Int.plus(right: FixedNumber) = FixedNumber.from(this) + right

@Throws(FixedPointException::class)
operator fun Long.plus(right: FixedNumber) = FixedNumber.from(this) + right

@Throws(FixedPointException::class)
operator fun Float.plus(right: FixedNumber) = FixedNumber.from(this) + right

@Throws(FixedPointException::class)
operator fun Double.plus(right: FixedNumber) = FixedNumber.from(this) + right

@Throws(FixedPointException::class)
operator fun Int.minus(right: FixedNumber) = FixedNumber.from(this) - right

@Throws(FixedPointException::class)
operator fun Long.minus(right: FixedNumber) = FixedNumber.from(this) - right

@Throws(FixedPointException::class)
operator fun Float.minus(right: FixedNumber) = FixedNumber.from(this) - right

@Throws(FixedPointException::class)
operator fun Double.minus(right: FixedNumber) = FixedNumber.from(this) - right

@Throws(FixedPointException::class)
operator fun Int.times(right: FixedNumber) = right * this

@Throws(FixedPointException::class)
operator fun Long.times(right: FixedNumber) = right * this

@Throws(FixedPointException::class)
operator fun Float.times(right: FixedNumber) = right * this

@Throws(FixedPointException::class)
operator fun Double.times(right: FixedNumber) = right * this

@Throws(FixedPointException::class)
operator fun Int.div(right: FixedNumber) = FixedNumber.from(this) / right

@Throws(FixedPointException::class)
operator fun Long.div(right: FixedNumber) = FixedNumber.from(this) / right

@Throws(FixedPointException::class)
operator fun Float.div(right: FixedNumber) = FixedNumber.from(this) / right

@Throws(FixedPointException::class)
operator fun Double.div(right: FixedNumber) = FixedNumber.from(this) / right

operator fun Int.compareTo(right: FixedNumber) = FixedNumber.from(this).compareTo(right)

operator fun Long.compareTo(right: FixedNumber) = FixedNumber.from(this).compareTo(right)

operator fun Float.compareTo(right: FixedNumber) = FixedNumber.from(this).compareTo(right)

operator fun Double.compareTo(right: FixedNumber) = FixedNumber.from(this).compareTo(right)

@Throws(FixedPointException::class)
fun abs(value: FixedNumber) = if (value.raw != Int.MIN_VALUE) FixedNumber.raw(kotlin.math.abs(value.raw))
		else throw FixedPointException("Can't represent abs of min value")

fun min(a: FixedNumber, b: FixedNumber) = FixedNumber.raw(kotlin.math.min(a.raw, b.raw))

fun max(a: FixedNumber, b: FixedNumber) = FixedNumber.raw(kotlin.math.max(a.raw, b.raw))
