package fixie.generator.quantity

import fixie.generator.number.FloatType
import java.io.PrintWriter
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

abstract class QuantityClassGenerator<T : QuantityClass>(
	protected val writer: PrintWriter,
	protected val quantity: T,
	protected val packageName: String
) {
	open fun generate() {
		generateClassPrefix()
		generateToDouble()
		generateToString()
		generateArithmetic()
		generateCompanionObject()
		writer.println("}")
		generateExtensionFunctions()
		generateMathFunctions()
	}

	protected abstract fun getInternalTypeName(): String

	protected abstract fun getImports(): Array<String>

	open fun generateClassHeader() {
		writer.println("@JvmInline")
		writer.println(
			"value class ${quantity.className} internal constructor(val value: ${getInternalTypeName()}) " +
					": Comparable<${quantity.className}> {"
		)
	}

	protected open fun generateClassPrefix() {
		val currentTime = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"))
		writer.println("// Generated by fixie at $currentTime")
		writer.println("package $packageName")

		val imports = getImports()
		if (imports.isNotEmpty()) {
			writer.println()
			for (import in imports) writer.println("import $import")
		}
		writer.println()
		generateClassHeader()
	}

	protected open fun generateToDoubleComment() {
		throw UnsupportedOperationException("Subclasses with exactly 1 unit must override this method")
	}

	protected open fun generateToDouble() {
		writer.println()
		val units = quantity.getSupportedUnits()

		if (units.isEmpty()) throw IllegalArgumentException("There are no units")

		val floatType = when (quantity) {
			is FloatQuantityClass -> quantity.floatType
			is HybridQuantityClass -> quantity.floatType
			else -> null
		}
		val doubleConversion = if (floatType?.numBytes == 8) "" else ".toDouble()"

		writer.println()
		if (quantity.getNumberOfUnits() == 1) {
			generateToDoubleComment()

			writer.println("\tfun toDouble() = value$doubleConversion")
		} else {
			writer.println("\tfun toDouble(unit: ${units[0].enumName}) = when (unit) {")
			for (unit in units) {
				val conversion = if (unit.relativeSize == 1.0) "" else " * ${1.0 / unit.relativeSize}"
				writer.println("\t\t${unit.enumName}.${unit.name} -> value$doubleConversion$conversion")
			}
			if (quantity.getNumberOfUnits() > units.size) {
				writer.println("\t\telse -> throw IllegalArgumentException(\"Unsupported unit \$unit\")")
			}
			writer.println("\t}")
		}
	}

	protected abstract fun generateToString()

	abstract fun generateArithmetic()

	protected abstract fun generateCompanionContent()

	protected open fun generateCompanionObject() {
		writer.println()
		writer.println("\tcompanion object {")
		generateCompanionContent()
		writer.println("\t}")
	}

	protected abstract fun generateExtensionFunctions()

	protected fun generateNumberUnitExtensionFunctions(typeName: String) {
		for (unit in quantity.getSupportedUnits()) {
			writer.println()
			writer.println("val $typeName.${unit.extensionName}")
			writer.println("\tget() = ${quantity.className}.${unit.name} * this")
		}
	}

	abstract fun generateMathFunctions()

	fun generateFloatCompanionContent(floatType: FloatType) {
		val suffix = if (floatType.numBytes == 4) "f" else ""
		writer.println("\t\tfun raw(value: ${floatType.typeName}) = ${quantity.className}(value)")
		writer.println()
		for (unit in quantity.getSupportedUnits()) {
			writer.println("\t\tval ${unit.name} = ${quantity.className}(${unit.relativeSize}$suffix)")
		}
	}
}
