name: Testing on various Java versions on Linux, Windows, and MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        jdk: [ 11, 21 ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
    - run: './gradlew shadowJar'
    - run: 'java -jar generator-tester/build/libs/generator-tester-all.jar'
    - run: './gradlew test'
    - run: 'java -jar generator-tester/build/libs/generator-tester-all.jar check'